version: "3.8"
services:
  backend:
    build: "./backend"
    container_name: geolocation_backend
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/backend"
      - "/backend/node_modules"

  frontend:
    build: "./frontend"
    container_name: geolocation_frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    stdin_open: true
    tty: true

